---
version: '3'
services:

  producer:
    build: ./kafka_producer
    volumes:
      - ./tmp/access/:/app/access/
      - ./env/my-franz-ivan.env:/app/.env

  consumer:
    build: ./kafka_consumer
    volumes:
      - ./tmp/access/:/app/access/
      - ./env/my-franz-ivan.env:/app/.env