apiVersion: apps/v1
kind: Deployment
metadata:
  name: franz-ivan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: franz-ivan
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: franz-ivan
    spec:
      containers:
      - image: vitekjede/franz-ivan-producer
        name: producer
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            cpu: 10m
            memory: 128Mi
        env:
        - name: CRYPTO_PAIR
          value: "btcusd"
        - name: KAFKA_TOPIC
          value: "crypto_prices"
        - name: KAFKA_HOST_PORT
          value: "kafka-franz-ivan-vit-de84.aivencloud.com:10235"
        - name: KAFKA_SSL_CAFILE
          value: "/app/access/ca.pem"
        - name: KAFKA_SSL_CERTFILE
          value: "/app/access/service.cert"
        - name: KAFKA_SSL_KEYFILE
          value: "/app/access/service.key"
        - name: LOGGING_LEVEL
          value: "DEBUG"
        volumeMounts: 
          - mountPath: "/app/access"
            name: kafka-secret
            readOnly: true

      - image: vitekjede/franz-ivan-consumer
        name: consumer
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            cpu: 10m
            memory: 128Mi
        env:
        - name: CRYPTO_PAIR
          value: "btcusd"
        - name: KAFKA_TOPIC
          value: "crypto_prices"
        - name: KAFKA_HOST_PORT
          value: "kafka-franz-ivan-vit-de84.aivencloud.com:10235"
        - name: KAFKA_SSL_CAFILE
          value: "/app/access/ca.pem"
        - name: KAFKA_SSL_CERTFILE
          value: "/app/access/service.cert"
        - name: KAFKA_SSL_KEYFILE
          value: "/app/access/service.key"
        - name: DB_HOST
          value: "postgres-franz-ivan-vit-de84.aivencloud.com"
        - name: DB_PORT
          value: "10233"
        - name: DB_NAME
          value: "crypto_prices"
        - name: DB_USER
          value: <<db-user-here>>
        - name: DB_PASS
          value: <<db-pass-here>>
        - name: LOGGING_LEVEL
          value: "DEBUG"
        volumeMounts: 
          - mountPath: "/app/access/"
            name: kafka-secret
            readOnly: true
      
      volumes:
        - name: kafka-secret
          secret:
            secretName: kafka-secret
